name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download terraform-bump
        run: |
          curl -sLJO https://github.com/mrasu/terraform-bump/releases/latest/download/terraform-bump-linux-amd64.tar.gz
          tar -xzf terraform-bump-linux-amd64.tar.gz
          chmod +x terraform-bump
          sudo mv terraform-bump /usr/local/bin/

      - name: Determine version
        run: terraform-bump

      - name: Update version tag
        run: |
          VERSION=$(cat .terraform-bump/release-version)
          git tag -a "${VERSION}" -m "Version ${VERSION}"
          git push --tags
