---
name: Increment Version Tag
on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Increment version tag
        run: |
          echo "Tagging version ${{ steps.version.outputs.version }}"
          git tag "${{ steps.version.outputs.version }}"

      - name: Push tag
        run: |
          git push origin "${{ steps.version.outputs.version }}"