name: Increment Version Tag
on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver

      - name: Check commit message
        run: |
          commit_message=$(cat "${GITHUB_REF}" | head -n 1)
          if [[ "${commit_message}" =~ "feat" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}" | sed 's/\.[0-9]*$//')
            echo "Incrementing major version to ${version}."
            version=$(expr "${version}" + 1)
            tag_name="v${version}"
          elif [[ "${commit_message}" =~ "fix" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}" | sed 's/\.[0-9]*$//')
            echo "Incrementing minor version to ${version}."
            version=$(expr "${version}" + 1)
            tag_name="v${version}"
          elif [[ "${commit_message}" =~ "docs" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}")
            echo "Patch version to ${version}."
            version=$(echo "${version}" | sed 's/\.[0-9]*$//')
            version=$(expr "${version}" + 1)
            tag_name="v${version}"
          elif [[ "${commit_message}" =~ "chore" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}")
            echo "Patch version to ${version}."
            version=$(echo "${version}" | sed 's/\.[0-9]*$//')
            version=$(expr "${version}" + 1)
            tag_name="v${version}"
          else
            echo "Unknown commit type, skipping version increment."
          fi

      - name: Increment version tag
        run: |
          echo "Tagging version ${{ tag_name }}"
          git tag "${{ tag_name }}"

      - name: Push tag
        run: |
          git push origin "${{ tag_name }}"