name: Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install semver
        run: npm install --global semver

      - name: Bump Version
        run: |
          # Get the latest commit message
          LATEST_COMMIT=$(git log -1 --pretty=format:%s)

          # Determine version bump based on the commit message
          if [[ "$LATEST_COMMIT" == *"#major"* ]]; then
            BUMP_TYPE="major"
          elif [[ "$LATEST_COMMIT" == *"#minor"* ]]; then
            BUMP_TYPE="minor"
          else
            BUMP_TYPE="patch"
          fi

          # Read the current version
          CURRENT_VERSION=$(cat version.txt)

          # Bump the version
          NEW_VERSION=$(semver --increment $BUMP_TYPE $CURRENT_VERSION)

          # Update the version.txt file
          echo $NEW_VERSION > version.txt

          echo "Version bumped to $NEW_VERSION"

          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Bump version" --allow-empty
          git push origin HEAD:main
