name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Commit Messages
        id: extract_messages
        run: |
          echo "::set-output name=messages::$(git log --pretty=format:%s)"

      - name: Determine Version Bump
        id: version_bump
        run: |
          messages="${{ steps.extract_messages.outputs.messages }}"
          if echo "$messages" | grep -iqE '#major'; then
            echo "::set-output name=bump::major"
          elif echo "$messages" | grep -iqE '#minor'; then
            echo "::set-output name=bump::minor"
          else
            echo "::set-output name=bump::patch"
          fi

      - name: Get Previous Tag
        id: get_previous_tag
        run: |
          git fetch --tags
          echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags)"

      - name: Bump Version
        id: bump_version
        run: |
          previous_tag="${{ steps.get_previous_tag.outputs.previous_tag }}"
          version_bump="${{ steps.version_bump.outputs.bump }}"
          new_version="$(semver bump $version_bump $previous_tag)"
          echo "::set-output name=version::$new_version"

      - name: Create Tag
        id: create_tag
        run: |
          new_version="${{ steps.bump_version.outputs.version }}"
          git tag $new_version
          echo "::set-output name=tag::$new_version"
          git push origin $new_version
