name: Increment Version Tag
on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Check commit message
        run: |
          commit_message=$(cat "${GITHUB_REF}" | head -n 1)
          if [[ "${commit_message}" =~ "feat" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}" | sed 's/\.[0-9]*$//')
            echo "Incrementing major version to ${version}."
            version=$(expr "${version}" + 1)
          elif [[ "${commit_message}" =~ "fix" ]]; then
            version=$(echo "${{ steps.version.outputs.version }}" | sed 's/\.[0-9]*$//')
            echo "Incrementing minor version to ${version}."
            version=$(expr "${version}" + 1)
          else
            echo "No version increment needed."
          fi

      - name: Increment version tag
        run: |
          echo "Tagging version ${version}"
          git tag "${version}"

      - name: Push tag
        run: |
          git push origin "${version}"