name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version
        id: determine_version
        run: |
          VERSION=$(git describe --abbrev=0 --tags)
          if [[ $VERSION =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
          else
            echo "Invalid version tag"
            exit 1
          fi

          COMMIT_MESSAGES=$(git log $(git describe --abbrev=0 --tags)..HEAD --pretty=format:"%s")
          if [[ $COMMIT_MESSAGES =~ \[MAJOR\] ]]; then
            ((MAJOR+=1))
            MINOR=0
            PATCH=0
          elif [[ $COMMIT_MESSAGES =~ \[MINOR\] ]]; then
            ((MINOR+=1))
            PATCH=0
          else
            ((PATCH+=1))
          fi

          echo "::set-output name=major::$MAJOR"
          echo "::set-output name=minor::$MINOR"
          echo "::set-output name=patch::$PATCH"

      - name: Update version tag
        run: |
          echo "${MAJOR}.${MINOR}.${PATCH}" > version.txt
          git tag -a "${MAJOR}.${MINOR}.${PATCH}" -m "Version ${MAJOR}.${MINOR}.${PATCH}"
          git push --tags
