name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install terraform-bump
        run: npm install -g terraform-bump

      - name: Determine version
        run: npx terraform-bump

      - name: Update version tag
        run: |
          VERSION=$(cat .terraform-bump/release-version)
          git tag -a "${VERSION}" -m "Version ${VERSION}"
          git push --tags
