name: Version Bump
on:
  push:
    branches:
      - main
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install semver
        run: pip install semver

      - name: Get Latest Commit Message
        run: |
          latest_commit_message=$(git log -1 --pretty=%B)
          echo "::set-output name=commit_message::$latest_commit_message"
        id: commit_message

      - name: Bump Version
        run: |
          python bump_version.py "${{ steps.commit_message.outputs.commit_message }}" "${{ steps.previous_tag.outputs.tag }}"
        id: bump_version
