name: Version Bump
on:
  push:
    branches:
      - main
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install semver
        run: pip install semver

      - name: Bump Version
        run: |
          python bump_version.py ${{ github.event.inputs.bump_type }}
        working-directory: .
